title: swaggerstats.io
email: sv2@slana.tech
description: > # this means to ignore newlines until "baseurl:"
  swagger-stats module collects and monitors REST API statistics in node express app using Swagger API specification or express routes
baseurl: "/pages-test" # the subpath of your site, e.g. /blog
url: "https://sv2.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sv2

# Build settings
markdown: kramdown

highlighter: rouge

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  - documentation
